/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as FollowUpRouteImport } from './routes/follow-up'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OutstandingRouteImport } from './routes/outstanding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerCaseTrackingRouteImport } from './routes/owner.case-tracking'
import { Route as OwnerControlRouteImport } from './routes/owner.control'
import { Route as OwnerFollowupRulesRouteImport } from './routes/owner.followup-rules'
import { Route as OwnerHealthRouteImport } from './routes/owner.health'
import { Route as OwnerHolidaysRouteImport } from './routes/owner.holidays'
import { Route as OwnerImportRouteImport } from './routes/owner.import'
import { Route as OwnerIncentivesRouteImport } from './routes/owner.incentives'
import { Route as OwnerPaymentAdjustmentsRouteImport } from './routes/owner.payment-adjustments'
import { Route as OwnerReportsRouteImport } from './routes/owner.reports'
import { Route as OwnerStaffRouteImport } from './routes/owner.staff'
import { Route as OwnerWinbackTiersRouteImport } from './routes/owner.winback-tiers'
import { Route as PatientIdRouteImport } from './routes/patient.$id'
import { Route as PayIdRouteImport } from './routes/pay.$id'
import { Route as PharmacyIndexRouteImport } from './routes/pharmacy.index'
import { Route as PharmacyInventoryRouteImport } from './routes/pharmacy.inventory'
import { Route as PharmacyMasterRouteImport } from './routes/pharmacy.master'
import { Route as DoctorCaseIndexRouteImport } from './routes/doctor.case.index'
import { Route as DoctorCaseReferenceRouteImport } from './routes/doctor.case.reference'
import { Route as DoctorRxIndexRouteImport } from './routes/doctor.rx.index'
import { Route as DoctorRxDashboardRouteImport } from './routes/doctor.rx.dashboard'
import { Route as DoctorRxHistoryRouteImport } from './routes/doctor.rx.history'
import { Route as PharmacyDispenseTokenRouteImport } from './routes/pharmacy.dispense.$token'
import { Route as DoctorCaseFormTokenRouteImport } from './routes/doctor.case.form.$token'
import { Route as DoctorRxConsultTokenRouteImport } from './routes/doctor.rx.consult.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpRoute = FollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OutstandingRoute = OutstandingRouteImport.update({
  id: '/outstanding',
  path: '/outstanding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerCaseTrackingRoute = OwnerCaseTrackingRouteImport.update({
  id: '/owner/case-tracking',
  path: '/owner/case-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerControlRoute = OwnerControlRouteImport.update({
  id: '/owner/control',
  path: '/owner/control',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerFollowupRulesRoute = OwnerFollowupRulesRouteImport.update({
  id: '/owner/followup-rules',
  path: '/owner/followup-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerHealthRoute = OwnerHealthRouteImport.update({
  id: '/owner/health',
  path: '/owner/health',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerHolidaysRoute = OwnerHolidaysRouteImport.update({
  id: '/owner/holidays',
  path: '/owner/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerImportRoute = OwnerImportRouteImport.update({
  id: '/owner/import',
  path: '/owner/import',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIncentivesRoute = OwnerIncentivesRouteImport.update({
  id: '/owner/incentives',
  path: '/owner/incentives',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPaymentAdjustmentsRoute = OwnerPaymentAdjustmentsRouteImport.update({
  id: '/owner/payment-adjustments',
  path: '/owner/payment-adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerReportsRoute = OwnerReportsRouteImport.update({
  id: '/owner/reports',
  path: '/owner/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerStaffRoute = OwnerStaffRouteImport.update({
  id: '/owner/staff',
  path: '/owner/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerWinbackTiersRoute = OwnerWinbackTiersRouteImport.update({
  id: '/owner/winback-tiers',
  path: '/owner/winback-tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdRoute = PatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyIndexRoute = PharmacyIndexRouteImport.update({
  id: '/pharmacy/',
  path: '/pharmacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyInventoryRoute = PharmacyInventoryRouteImport.update({
  id: '/pharmacy/inventory',
  path: '/pharmacy/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyMasterRoute = PharmacyMasterRouteImport.update({
  id: '/pharmacy/master',
  path: '/pharmacy/master',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorCaseIndexRoute = DoctorCaseIndexRouteImport.update({
  id: '/doctor/case/',
  path: '/doctor/case/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorCaseReferenceRoute = DoctorCaseReferenceRouteImport.update({
  id: '/doctor/case/reference',
  path: '/doctor/case/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRxIndexRoute = DoctorRxIndexRouteImport.update({
  id: '/doctor/rx/',
  path: '/doctor/rx/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRxDashboardRoute = DoctorRxDashboardRouteImport.update({
  id: '/doctor/rx/dashboard',
  path: '/doctor/rx/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRxHistoryRoute = DoctorRxHistoryRouteImport.update({
  id: '/doctor/rx/history',
  path: '/doctor/rx/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyDispenseTokenRoute = PharmacyDispenseTokenRouteImport.update({
  id: '/pharmacy/dispense/$token',
  path: '/pharmacy/dispense/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorCaseFormTokenRoute = DoctorCaseFormTokenRouteImport.update({
  id: '/doctor/case/form/$token',
  path: '/doctor/case/form/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRxConsultTokenRoute = DoctorRxConsultTokenRouteImport.update({
  id: '/doctor/rx/consult/$token',
  path: '/doctor/rx/consult/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/delivery': typeof DeliveryRoute
  '/follow-up': typeof FollowUpRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/outstanding': typeof OutstandingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/summary': typeof SummaryRoute
  '/tasks': typeof TasksRoute
  '/owner/case-tracking': typeof OwnerCaseTrackingRoute
  '/owner/control': typeof OwnerControlRoute
  '/owner/followup-rules': typeof OwnerFollowupRulesRoute
  '/owner/health': typeof OwnerHealthRoute
  '/owner/holidays': typeof OwnerHolidaysRoute
  '/owner/import': typeof OwnerImportRoute
  '/owner/incentives': typeof OwnerIncentivesRoute
  '/owner/payment-adjustments': typeof OwnerPaymentAdjustmentsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/winback-tiers': typeof OwnerWinbackTiersRoute
  '/patient/$id': typeof PatientIdRoute
  '/pay/$id': typeof PayIdRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/master': typeof PharmacyMasterRoute
  '/doctor/': typeof DoctorIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/doctor/case/reference': typeof DoctorCaseReferenceRoute
  '/doctor/rx/dashboard': typeof DoctorRxDashboardRoute
  '/doctor/rx/history': typeof DoctorRxHistoryRoute
  '/pharmacy/dispense/$token': typeof PharmacyDispenseTokenRoute
  '/doctor/case/': typeof DoctorCaseIndexRoute
  '/doctor/rx/': typeof DoctorRxIndexRoute
  '/doctor/case/form/$token': typeof DoctorCaseFormTokenRoute
  '/doctor/rx/consult/$token': typeof DoctorRxConsultTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/delivery': typeof DeliveryRoute
  '/follow-up': typeof FollowUpRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/outstanding': typeof OutstandingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/summary': typeof SummaryRoute
  '/tasks': typeof TasksRoute
  '/owner/case-tracking': typeof OwnerCaseTrackingRoute
  '/owner/control': typeof OwnerControlRoute
  '/owner/followup-rules': typeof OwnerFollowupRulesRoute
  '/owner/health': typeof OwnerHealthRoute
  '/owner/holidays': typeof OwnerHolidaysRoute
  '/owner/import': typeof OwnerImportRoute
  '/owner/incentives': typeof OwnerIncentivesRoute
  '/owner/payment-adjustments': typeof OwnerPaymentAdjustmentsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/winback-tiers': typeof OwnerWinbackTiersRoute
  '/patient/$id': typeof PatientIdRoute
  '/pay/$id': typeof PayIdRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/master': typeof PharmacyMasterRoute
  '/doctor': typeof DoctorIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/pharmacy': typeof PharmacyIndexRoute
  '/doctor/case/reference': typeof DoctorCaseReferenceRoute
  '/doctor/rx/dashboard': typeof DoctorRxDashboardRoute
  '/doctor/rx/history': typeof DoctorRxHistoryRoute
  '/pharmacy/dispense/$token': typeof PharmacyDispenseTokenRoute
  '/doctor/case': typeof DoctorCaseIndexRoute
  '/doctor/rx': typeof DoctorRxIndexRoute
  '/doctor/case/form/$token': typeof DoctorCaseFormTokenRoute
  '/doctor/rx/consult/$token': typeof DoctorRxConsultTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/delivery': typeof DeliveryRoute
  '/follow-up': typeof FollowUpRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/outstanding': typeof OutstandingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/summary': typeof SummaryRoute
  '/tasks': typeof TasksRoute
  '/owner/case-tracking': typeof OwnerCaseTrackingRoute
  '/owner/control': typeof OwnerControlRoute
  '/owner/followup-rules': typeof OwnerFollowupRulesRoute
  '/owner/health': typeof OwnerHealthRoute
  '/owner/holidays': typeof OwnerHolidaysRoute
  '/owner/import': typeof OwnerImportRoute
  '/owner/incentives': typeof OwnerIncentivesRoute
  '/owner/payment-adjustments': typeof OwnerPaymentAdjustmentsRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/staff': typeof OwnerStaffRoute
  '/owner/winback-tiers': typeof OwnerWinbackTiersRoute
  '/patient/$id': typeof PatientIdRoute
  '/pay/$id': typeof PayIdRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/master': typeof PharmacyMasterRoute
  '/doctor/': typeof DoctorIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/doctor/case/reference': typeof DoctorCaseReferenceRoute
  '/doctor/rx/dashboard': typeof DoctorRxDashboardRoute
  '/doctor/rx/history': typeof DoctorRxHistoryRoute
  '/pharmacy/dispense/$token': typeof PharmacyDispenseTokenRoute
  '/doctor/case/': typeof DoctorCaseIndexRoute
  '/doctor/rx/': typeof DoctorRxIndexRoute
  '/doctor/case/form/$token': typeof DoctorCaseFormTokenRoute
  '/doctor/rx/consult/$token': typeof DoctorRxConsultTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/delivery'
    | '/follow-up'
    | '/leads'
    | '/login'
    | '/outstanding'
    | '/register'
    | '/search'
    | '/summary'
    | '/tasks'
    | '/owner/case-tracking'
    | '/owner/control'
    | '/owner/followup-rules'
    | '/owner/health'
    | '/owner/holidays'
    | '/owner/import'
    | '/owner/incentives'
    | '/owner/payment-adjustments'
    | '/owner/reports'
    | '/owner/staff'
    | '/owner/winback-tiers'
    | '/patient/$id'
    | '/pay/$id'
    | '/pharmacy/inventory'
    | '/pharmacy/master'
    | '/doctor/'
    | '/owner/'
    | '/pharmacy/'
    | '/doctor/case/reference'
    | '/doctor/rx/dashboard'
    | '/doctor/rx/history'
    | '/pharmacy/dispense/$token'
    | '/doctor/case/'
    | '/doctor/rx/'
    | '/doctor/case/form/$token'
    | '/doctor/rx/consult/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/delivery'
    | '/follow-up'
    | '/leads'
    | '/login'
    | '/outstanding'
    | '/register'
    | '/search'
    | '/summary'
    | '/tasks'
    | '/owner/case-tracking'
    | '/owner/control'
    | '/owner/followup-rules'
    | '/owner/health'
    | '/owner/holidays'
    | '/owner/import'
    | '/owner/incentives'
    | '/owner/payment-adjustments'
    | '/owner/reports'
    | '/owner/staff'
    | '/owner/winback-tiers'
    | '/patient/$id'
    | '/pay/$id'
    | '/pharmacy/inventory'
    | '/pharmacy/master'
    | '/doctor'
    | '/owner'
    | '/pharmacy'
    | '/doctor/case/reference'
    | '/doctor/rx/dashboard'
    | '/doctor/rx/history'
    | '/pharmacy/dispense/$token'
    | '/doctor/case'
    | '/doctor/rx'
    | '/doctor/case/form/$token'
    | '/doctor/rx/consult/$token'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/delivery'
    | '/follow-up'
    | '/leads'
    | '/login'
    | '/outstanding'
    | '/register'
    | '/search'
    | '/summary'
    | '/tasks'
    | '/owner/case-tracking'
    | '/owner/control'
    | '/owner/followup-rules'
    | '/owner/health'
    | '/owner/holidays'
    | '/owner/import'
    | '/owner/incentives'
    | '/owner/payment-adjustments'
    | '/owner/reports'
    | '/owner/staff'
    | '/owner/winback-tiers'
    | '/patient/$id'
    | '/pay/$id'
    | '/pharmacy/inventory'
    | '/pharmacy/master'
    | '/doctor/'
    | '/owner/'
    | '/pharmacy/'
    | '/doctor/case/reference'
    | '/doctor/rx/dashboard'
    | '/doctor/rx/history'
    | '/pharmacy/dispense/$token'
    | '/doctor/case/'
    | '/doctor/rx/'
    | '/doctor/case/form/$token'
    | '/doctor/rx/consult/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  DeliveryRoute: typeof DeliveryRoute
  FollowUpRoute: typeof FollowUpRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  OutstandingRoute: typeof OutstandingRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SummaryRoute: typeof SummaryRoute
  TasksRoute: typeof TasksRoute
  OwnerCaseTrackingRoute: typeof OwnerCaseTrackingRoute
  OwnerControlRoute: typeof OwnerControlRoute
  OwnerFollowupRulesRoute: typeof OwnerFollowupRulesRoute
  OwnerHealthRoute: typeof OwnerHealthRoute
  OwnerHolidaysRoute: typeof OwnerHolidaysRoute
  OwnerImportRoute: typeof OwnerImportRoute
  OwnerIncentivesRoute: typeof OwnerIncentivesRoute
  OwnerPaymentAdjustmentsRoute: typeof OwnerPaymentAdjustmentsRoute
  OwnerReportsRoute: typeof OwnerReportsRoute
  OwnerStaffRoute: typeof OwnerStaffRoute
  OwnerWinbackTiersRoute: typeof OwnerWinbackTiersRoute
  PatientIdRoute: typeof PatientIdRoute
  PayIdRoute: typeof PayIdRoute
  PharmacyInventoryRoute: typeof PharmacyInventoryRoute
  PharmacyMasterRoute: typeof PharmacyMasterRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  PharmacyIndexRoute: typeof PharmacyIndexRoute
  DoctorCaseReferenceRoute: typeof DoctorCaseReferenceRoute
  DoctorRxDashboardRoute: typeof DoctorRxDashboardRoute
  DoctorRxHistoryRoute: typeof DoctorRxHistoryRoute
  PharmacyDispenseTokenRoute: typeof PharmacyDispenseTokenRoute
  DoctorCaseIndexRoute: typeof DoctorCaseIndexRoute
  DoctorRxIndexRoute: typeof DoctorRxIndexRoute
  DoctorCaseFormTokenRoute: typeof DoctorCaseFormTokenRoute
  DoctorRxConsultTokenRoute: typeof DoctorRxConsultTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-up': {
      id: '/follow-up'
      path: '/follow-up'
      fullPath: '/follow-up'
      preLoaderRoute: typeof FollowUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outstanding': {
      id: '/outstanding'
      path: '/outstanding'
      fullPath: '/outstanding'
      preLoaderRoute: typeof OutstandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/case-tracking': {
      id: '/owner/case-tracking'
      path: '/owner/case-tracking'
      fullPath: '/owner/case-tracking'
      preLoaderRoute: typeof OwnerCaseTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/control': {
      id: '/owner/control'
      path: '/owner/control'
      fullPath: '/owner/control'
      preLoaderRoute: typeof OwnerControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/followup-rules': {
      id: '/owner/followup-rules'
      path: '/owner/followup-rules'
      fullPath: '/owner/followup-rules'
      preLoaderRoute: typeof OwnerFollowupRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/health': {
      id: '/owner/health'
      path: '/owner/health'
      fullPath: '/owner/health'
      preLoaderRoute: typeof OwnerHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/holidays': {
      id: '/owner/holidays'
      path: '/owner/holidays'
      fullPath: '/owner/holidays'
      preLoaderRoute: typeof OwnerHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/import': {
      id: '/owner/import'
      path: '/owner/import'
      fullPath: '/owner/import'
      preLoaderRoute: typeof OwnerImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/incentives': {
      id: '/owner/incentives'
      path: '/owner/incentives'
      fullPath: '/owner/incentives'
      preLoaderRoute: typeof OwnerIncentivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/payment-adjustments': {
      id: '/owner/payment-adjustments'
      path: '/owner/payment-adjustments'
      fullPath: '/owner/payment-adjustments'
      preLoaderRoute: typeof OwnerPaymentAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/reports': {
      id: '/owner/reports'
      path: '/owner/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof OwnerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/staff': {
      id: '/owner/staff'
      path: '/owner/staff'
      fullPath: '/owner/staff'
      preLoaderRoute: typeof OwnerStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/winback-tiers': {
      id: '/owner/winback-tiers'
      path: '/owner/winback-tiers'
      fullPath: '/owner/winback-tiers'
      preLoaderRoute: typeof OwnerWinbackTiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id': {
      id: '/patient/$id'
      path: '/patient/$id'
      fullPath: '/patient/$id'
      preLoaderRoute: typeof PatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/': {
      id: '/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof PharmacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/inventory': {
      id: '/pharmacy/inventory'
      path: '/pharmacy/inventory'
      fullPath: '/pharmacy/inventory'
      preLoaderRoute: typeof PharmacyInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/master': {
      id: '/pharmacy/master'
      path: '/pharmacy/master'
      fullPath: '/pharmacy/master'
      preLoaderRoute: typeof PharmacyMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/case/': {
      id: '/doctor/case/'
      path: '/doctor/case'
      fullPath: '/doctor/case/'
      preLoaderRoute: typeof DoctorCaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/case/reference': {
      id: '/doctor/case/reference'
      path: '/doctor/case/reference'
      fullPath: '/doctor/case/reference'
      preLoaderRoute: typeof DoctorCaseReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/rx/': {
      id: '/doctor/rx/'
      path: '/doctor/rx'
      fullPath: '/doctor/rx/'
      preLoaderRoute: typeof DoctorRxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/rx/dashboard': {
      id: '/doctor/rx/dashboard'
      path: '/doctor/rx/dashboard'
      fullPath: '/doctor/rx/dashboard'
      preLoaderRoute: typeof DoctorRxDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/rx/history': {
      id: '/doctor/rx/history'
      path: '/doctor/rx/history'
      fullPath: '/doctor/rx/history'
      preLoaderRoute: typeof DoctorRxHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/dispense/$token': {
      id: '/pharmacy/dispense/$token'
      path: '/pharmacy/dispense/$token'
      fullPath: '/pharmacy/dispense/$token'
      preLoaderRoute: typeof PharmacyDispenseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/case/form/$token': {
      id: '/doctor/case/form/$token'
      path: '/doctor/case/form/$token'
      fullPath: '/doctor/case/form/$token'
      preLoaderRoute: typeof DoctorCaseFormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/rx/consult/$token': {
      id: '/doctor/rx/consult/$token'
      path: '/doctor/rx/consult/$token'
      fullPath: '/doctor/rx/consult/$token'
      preLoaderRoute: typeof DoctorRxConsultTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  DeliveryRoute: DeliveryRoute,
  FollowUpRoute: FollowUpRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  OutstandingRoute: OutstandingRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SummaryRoute: SummaryRoute,
  TasksRoute: TasksRoute,
  OwnerCaseTrackingRoute: OwnerCaseTrackingRoute,
  OwnerControlRoute: OwnerControlRoute,
  OwnerFollowupRulesRoute: OwnerFollowupRulesRoute,
  OwnerHealthRoute: OwnerHealthRoute,
  OwnerHolidaysRoute: OwnerHolidaysRoute,
  OwnerImportRoute: OwnerImportRoute,
  OwnerIncentivesRoute: OwnerIncentivesRoute,
  OwnerPaymentAdjustmentsRoute: OwnerPaymentAdjustmentsRoute,
  OwnerReportsRoute: OwnerReportsRoute,
  OwnerStaffRoute: OwnerStaffRoute,
  OwnerWinbackTiersRoute: OwnerWinbackTiersRoute,
  PatientIdRoute: PatientIdRoute,
  PayIdRoute: PayIdRoute,
  PharmacyInventoryRoute: PharmacyInventoryRoute,
  PharmacyMasterRoute: PharmacyMasterRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  PharmacyIndexRoute: PharmacyIndexRoute,
  DoctorCaseReferenceRoute: DoctorCaseReferenceRoute,
  DoctorRxDashboardRoute: DoctorRxDashboardRoute,
  DoctorRxHistoryRoute: DoctorRxHistoryRoute,
  PharmacyDispenseTokenRoute: PharmacyDispenseTokenRoute,
  DoctorCaseIndexRoute: DoctorCaseIndexRoute,
  DoctorRxIndexRoute: DoctorRxIndexRoute,
  DoctorCaseFormTokenRoute: DoctorCaseFormTokenRoute,
  DoctorRxConsultTokenRoute: DoctorRxConsultTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
